spring:
  profiles:
    active: dev

---
server:
  port: 8080

spring:
  profiles: dev     # 该环境仅修改了对应的数据库spring_cloud_test
  application:
    name: cloud-provider-department-config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///spring_cloud_test?serverTimezone=Asia/Shanghai&unicode=true&characterEncoding=UTF-8
    username: root
    password: P@ssw0rd

mybatis:
  type-aliases-package: vip.epss.domain
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版,直接配置Eureka Server的地址
      #defaultZone: http://localhost:7001/eureka
      #集群版,配置发布到多台集群服务器上
      defaultZone: http://eureka7040.com:7040/eureka/,http://eureka7050.com:7050/eureka/,http://eureka7060.com:7060/eureka/
  instance:
    # 修改在服务器上该实例的描述信息
    instance-id: cloud-provider-department-config-8080

# 使用actuator
info:
  app: springcloud2021
  comp: epss.vip
  author: epss
  
  
  
---
server:
  port: 8080

spring:
  profiles: test    # 该环境仅修改了对应的数据库spring_cloud_test_2
  application:
    name: cloud-provider-department-config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///spring_cloud_test_2?serverTimezone=Asia/Shanghai&unicode=true&characterEncoding=UTF-8
    username: root
    password: P@ssw0rd

mybatis:
  type-aliases-package: vip.epss.domain
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版,直接配置Eureka Server的地址
      #defaultZone: http://localhost:7001/eureka
      #集群版,配置发布到多台集群服务器上
      defaultZone: http://eureka7040.com:7040/eureka/,http://eureka7050.com:7050/eureka/,http://eureka7060.com:7060/eureka/
  instance:
    # 修改在服务器上该实例的描述信息
    instance-id: cloud-provider-department-config-8080

# 使用actuator
info:
  app: springcloud2021
  comp: epss.vip
  author: epss